{"level":"error","message":"Директория /home/alex/DApp-for-Business/backend/temp недоступна для записи: EACCES: permission denied, open '/home/alex/DApp-for-Business/backend/temp/.write-test'","timestamp":"2025-06-18T19:10:58.515Z"}
{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::8000","port":8000,"stack":"Error: listen EADDRINUSE: address already in use :::8000\n    at Server.setupListenHandle [as _listen2] (node:net:1908:16)\n    at listenInCluster (node:net:1965:12)\n    at Server.listen (node:net:2067:7)\n    at Object.<anonymous> (/home/alex/DApp-for-Business/backend/server.js:47:8)\n    at Module._compile (node:internal/modules/cjs/loader:1469:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)\n    at Module.load (node:internal/modules/cjs/loader:1288:32)\n    at Module._load (node:internal/modules/cjs/loader:1104:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:173:12)\n    at node:internal/main/run_main_module:28:49","syscall":"listen","timestamp":"2025-06-18T19:10:59.390Z"}
{"code":"EAI_AGAIN","errno":-3001,"hostname":"postgres","level":"error","message":"Unhandled Rejection: getaddrinfo EAI_AGAIN postgres","stack":"Error: getaddrinfo EAI_AGAIN postgres\n    at /home/alex/DApp-for-Business/backend/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async reinitPoolFromDbSettings (/home/alex/DApp-for-Business/backend/db.js:50:17)","syscall":"getaddrinfo","timestamp":"2025-06-18T19:11:11.251Z"}
{"level":"error","message":"Директория /home/alex/DApp-for-Business/backend/temp недоступна для записи: EACCES: permission denied, open '/home/alex/DApp-for-Business/backend/temp/.write-test'","timestamp":"2025-06-18T19:14:27.087Z"}
{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::8000","port":8000,"stack":"Error: listen EADDRINUSE: address already in use :::8000\n    at Server.setupListenHandle [as _listen2] (node:net:1908:16)\n    at listenInCluster (node:net:1965:12)\n    at Server.listen (node:net:2067:7)\n    at Object.<anonymous> (/home/alex/DApp-for-Business/backend/server.js:47:8)\n    at Module._compile (node:internal/modules/cjs/loader:1469:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)\n    at Module.load (node:internal/modules/cjs/loader:1288:32)\n    at Module._load (node:internal/modules/cjs/loader:1104:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:173:12)\n    at node:internal/main/run_main_module:28:49","syscall":"listen","timestamp":"2025-06-18T19:14:27.414Z"}
{"code":"EAI_AGAIN","errno":-3001,"hostname":"postgres","level":"error","message":"Unhandled Rejection: getaddrinfo EAI_AGAIN postgres","stack":"Error: getaddrinfo EAI_AGAIN postgres\n    at /home/alex/DApp-for-Business/backend/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async reinitPoolFromDbSettings (/home/alex/DApp-for-Business/backend/db.js:50:17)","syscall":"getaddrinfo","timestamp":"2025-06-18T19:14:40.959Z"}
{"level":"error","message":"Директория /home/alex/DApp-for-Business/backend/temp недоступна для записи: EACCES: permission denied, open '/home/alex/DApp-for-Business/backend/temp/.write-test'","timestamp":"2025-06-18T19:16:21.596Z"}
{"code":"EAI_AGAIN","errno":-3001,"hostname":"postgres","level":"error","message":"Unhandled Rejection: getaddrinfo EAI_AGAIN postgres","stack":"Error: getaddrinfo EAI_AGAIN postgres\n    at /home/alex/DApp-for-Business/backend/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async reinitPoolFromDbSettings (/home/alex/DApp-for-Business/backend/db.js:50:17)","syscall":"getaddrinfo","timestamp":"2025-06-18T19:16:35.178Z"}
{"ip":"::1","level":"error","message":"Error: getaddrinfo EAI_AGAIN postgres","method":"GET","stack":"Error: getaddrinfo EAI_AGAIN postgres\n    at /home/alex/DApp-for-Business/backend/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PGStore._asyncQuery (/home/alex/DApp-for-Business/backend/node_modules/connect-pg-simple/index.js:322:21)","timestamp":"2025-06-18T19:16:44.984Z","url":"/api/auth/identities"}
{"ip":"::1","level":"error","message":"Error: getaddrinfo EAI_AGAIN postgres","method":"GET","stack":"Error: getaddrinfo EAI_AGAIN postgres\n    at /home/alex/DApp-for-Business/backend/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PGStore._asyncQuery (/home/alex/DApp-for-Business/backend/node_modules/connect-pg-simple/index.js:322:21)","timestamp":"2025-06-18T19:17:33.983Z","url":"/api/auth/identities"}
{"level":"error","message":"[EmailBot] IMAP connection error: Timed out while authenticating with server","timestamp":"2025-06-18T19:24:31.727Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:24:31.728Z"}
{"level":"error","message":"[EmailBot] IMAP connection error: Timed out while authenticating with server","timestamp":"2025-06-18T19:24:47.815Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:24:47.817Z"}
{"level":"error","message":"[EmailBot] IMAP connection error: Timed out while authenticating with server","timestamp":"2025-06-18T19:25:01.594Z"}
{"code":"23505","constraint":"user_identities_provider_provider_id_key","detail":"Key (provider, provider_id)=(email, avtarabanov@gmail.com) already exists.","file":"nbtinsert.c","length":296,"level":"error","line":"666","message":"[IdentityService] Error saving identity email:avtarabanov@gmail.com for user 99: duplicate key value violates unique constraint \"user_identities_provider_provider_id_key\"","name":"error","routine":"_bt_check_unique","schema":"public","severity":"ERROR","stack":"error: duplicate key value violates unique constraint \"user_identities_provider_provider_id_key\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async IdentityService.saveIdentity (/app/services/identity-service.js:124:9)\n    at async IdentityService.findOrCreateUserWithRole (/app/services/identity-service.js:544:7)\n    at async /app/services/emailBot.js:140:48","table":"user_identities","timestamp":"2025-06-18T19:25:16.580Z"}
{"code":"23503","constraint":"messages_user_id_fkey","detail":"Key (user_id)=(99) is not present in table \"users\".","file":"ri_triggers.c","length":255,"level":"error","line":"2608","message":"Error processing incoming email: insert or update on table \"messages\" violates foreign key constraint \"messages_user_id_fkey\"","name":"error","routine":"ri_ReportViolation","schema":"public","severity":"ERROR","stack":"error: insert or update on table \"messages\" violates foreign key constraint \"messages_user_id_fkey\"\n    at /app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/services/emailBot.js:167:23","table":"messages","timestamp":"2025-06-18T19:27:06.840Z"}
{"code":"EPROTOCOL","command":"CONN","level":"error","message":"Error sending email: Invalid greeting. response=421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26: 421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26","response":"421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26","responseCode":421,"stack":"Error: Invalid greeting. response=421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26: 421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26\n    at SMTPConnection._actionGreeting (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1251:27)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)","timestamp":"2025-06-18T19:27:25.131Z"}
{"code":"EPROTOCOL","command":"CONN","level":"error","message":"Error processing incoming email: Invalid greeting. response=421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26: 421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26","response":"421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26","responseCode":421,"stack":"Error: Invalid greeting. response=421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26: 421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26\n    at SMTPConnection._actionGreeting (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1251:27)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)","timestamp":"2025-06-18T19:27:25.132Z"}
{"code":"EPROTOCOL","command":"CONN","level":"error","message":"Error sending email: Invalid greeting. response=421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26: 421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26","response":"421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26","responseCode":421,"stack":"Error: Invalid greeting. response=421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26: 421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26\n    at SMTPConnection._actionGreeting (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1251:27)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)","timestamp":"2025-06-18T19:27:25.590Z"}
{"code":"EPROTOCOL","command":"CONN","level":"error","message":"Error processing incoming email: Invalid greeting. response=421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26: 421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26","response":"421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26","responseCode":421,"stack":"Error: Invalid greeting. response=421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26: 421 4.7.0 smtp.hostland.ru Error: too many connections from 78.31.221.26\n    at SMTPConnection._actionGreeting (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1251:27)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)","timestamp":"2025-06-18T19:27:25.592Z"}
{"level":"error","message":"[EmailBot] IMAP connection error: Timed out while authenticating with server","timestamp":"2025-06-18T19:27:31.660Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:27:31.662Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:27:31.663Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:27:31.663Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:27:31.664Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:27:31.665Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:27:31.667Z"}
{"level":"error","message":"[EmailBot] IMAP connection error: Timed out while authenticating with server","timestamp":"2025-06-18T19:29:30.006Z"}
{"level":"error","message":"[EmailBot] IMAP connection error: Timed out while authenticating with server","timestamp":"2025-06-18T19:29:43.775Z"}
{"level":"error","message":"[EmailBot] IMAP connection error: Timed out while authenticating with server","timestamp":"2025-06-18T19:30:57.052Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:30:57.053Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:30:57.053Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:32:46.073Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-18T19:32:46.073Z"}
{"level":"error","message":"[EmailBot] IMAP connection error: Timed out while authenticating with server","timestamp":"2025-06-19T12:16:04.066Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:16:04.066Z"}
{"level":"error","message":"[EmailBot] IMAP connection error: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.096Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.097Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.097Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.097Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.098Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.098Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.098Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.099Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.099Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.100Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.100Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.100Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.101Z"}
{"level":"error","message":"IMAP connection error during check: Timed out while authenticating with server","timestamp":"2025-06-19T12:21:53.101Z"}
